apiVersion: v1
kind: Namespace
metadata:
  name: demo
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice
  namespace: demo
spec:
  selector:
    matchLabels:
      app: helloservice
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: shlomigonen/ossjapan:sha-a479369
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: helloservice
  namespace: demo
spec:
  selector:
    app: helloservice
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: demo-app-ingress
  namespace: demo
spec:
  rules:
  - host: a88521e248b034a0b936f577afc27bae-943030244.eu-central-1.elb.amazonaws.com
    http:
      paths:
      - backend:
          service:
            name: helloservice
            port:
              number: 80
        path: /
        pathType: Prefix



      
